tiny_llama:
  dataset:
    train_val_dir: 
    type: trac_white
  vision_encoder:
    vision_tower_config: 
      vision_tower: "cnn"
      # out_channels: 768
      out_channels: 256
      in_channels: 1

      # img_size: [32, 256, 256]
      # patch_size: [8, 64, 64]
      # in_channels: 1
      # hidden_size: 768
      # num_heads: 8
      # vision_select_layer: -1
      # vision_select_feature: cls_patch

    projector:
      image_size: [32, 256, 256]
      patch_size: [8, 64, 64]
      # in_dim: 2560
      out_channels: 256
      in_channels: 2048
      in_embed: 256
      out_embed: 2048
      # out_dim: 2048
      # hidden_dim: 1024
      # out_dim: 256
      layer_type: mlp
      layer_num: 1
      pooling_type: spatial
      pooling_size: 2
      # mm_projector_type: linear
      mm_projector_type: transpose
  
  bbox_predictor:
    bbox_type: anchor_v2
    bbox_head:
      in_channels: 1
      input_dim: 2048
      hidden_dim: 512
      num_classes: 1
      # max_bbox_len: 9
      max_bbox_len: 1
      normalize_coords: True
      coord_bounds: 
        x_min: 0
        x_max: 255
        y_min: 0
        y_max: 255
        z_min: 0
        z_max: 31

    
    mm_hidden_size: 512
    bbox3d_head_type: default
    bbox3d_projector_type: default
      


