data:
  data_root: "./data/"
  dataset: "trac_white"
  train_val_split: 0.8
  train_val_dir: /root/TracGPT-R3D/pseudo_3d/32_overlap_slices/1ad40bdc-da39-4dd8-9d3a-27ce00e754fa/train/data
  test_dir: /root/TracGPT-R3D/pseudo_3d/32_overlap_slices/1ad40bdc-da39-4dd8-9d3a-27ce00e754fa/test/data
  image_train_path: /root/VLMTrac/2d_data/train/image
  image_test_path: /root/VLMTrac/2d_data/test/image
  # train_sample: -1
  # val_sample: -1
  # test_sample: -1
  dataset_config: 
    only_2d: True

  train_sample: 4
  val_sample: 4
  test_sample: 4
  # train_sample: 500
  # val_sample: 100
  # test_sample: 100
  dataloader_pin_memory: False
  

general:
  max_eval: 1
  trainer: bbox_2d


model:
  tags: [llama, ViT]
  config:
    language_model: 
      name: meta-llama/Llama-3.2-1B
    vision_encoder:
      vision_tower_config: 
        vision_tower: vit3d
        img_size: [32, 256, 256]
        patch_size: [4, 16, 16]
        in_channels: 1
        # hidden_size: 2560
        # hidden_size: 512
        hidden_size: 256
        num_heads: 8
        vision_select_layer: -1
        vision_select_feature: cls_patch

      projector:
        image_size: [32, 256, 256]
        patch_size: [4, 16, 16]
        # in_dim: 2560
        out_channels: 256
        in_channels: 2048
        in_embed: 256
        out_embed: 2048
        # out_dim: 2048
        # hidden_dim: 1024
        # out_dim: 256
        layer_type: mlp
        layer_num: 1
        pooling_type: spatial
        pooling_size: 2
        # mm_projector_type: linear
        mm_projector_type: minigpt
    
      bbox_predictor:
        bbox_head:
          in_channels: 1
          input_dim: 2048
          hidden_dim: 512
          num_classes: 1
          # max_bbox_len: 9
          max_bbox_len: 1
          normalize_coords: True
          coord_bounds: 
            x_min: 0
            x_max: 255
            y_min: 0
            y_max: 255
            z_min: 0
            z_max: 31

        
        mm_hidden_size: 512
        bbox3d_head_type: default
        bbox3d_projector_type: default
          


training:
  output_dir: "./output"
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  num_train_epochs: 1
  logging_dir: "./logs"  
  eval_strategy: "steps"
  eval_steps: 200
  logging_steps: 50
  save_strategy: "steps"
  save_steps: 200
  learning_rate: 1e-4
  weight_decay: 0.01
  warmup_ratio: 0.1
  lr_scheduler_type: "cosine"
  gradient_accumulation_steps: 1
  gradient_checkpointing: false
  dataloader_num_workers: 4
  save_total_limit: 2
  load_best_model_at_end: true
  report_to: wandb
  remove_unused_columns: false
  seed: 42
  fp16: False
  bf16: False
  metric_for_best_model: precision
  greater_is_better: True
  # greater_is_better: False
  save_safetensors: False
  dataloader_pin_memory: False