data:
  data_root: "./data/"
  dataset: "trac_white"
  train_val_split: 0.8

  train_val_dir: pseudo_3d/32_all_slices/7cc980de-e632-4f11-9805-65acc291fcb7/train/data
  test_dir: pseudo_3d/32_all_slices/7cc980de-e632-4f11-9805-65acc291fcb7/test/data

  image_train_path: clean_data_s_chain/train/image
  image_test_path: clean_data_s_chain/test/image


  overfit_train: True
  original: True
  train_sample: 30
  val_sample: 10
  test_sample: 10

  # train_sample: -1
  # val_sample: -1
  # test_sample: -1
  dataloader_pin_memory: False
  

general:
  max_eval: 4
  trainer: standard
  collator: "standard"


  lora: True
  # lora_r: 8
  # lora_alpha: 16

  lora_r: 64
  lora_alpha: 128
  lora_dropout: 0.05
  lora_target_modules: ["q_proj", "k_proj", "v_proj", "o_proj","gate_proj", "up_proj", "down_proj",        
        "lm_head",                                  
        # "embed_tokens",
        ]
  lora_bias: "none"

model:
  tags: [llama, ViT]
  name: vit_llama
  config:
    language_model: 
      name: meta-llama/Llama-3.2-3B
    vision_encoder:
        pretrained_path: pretrained_ViT.bin
        vision_tower: vit3d
        img_size: [32, 256, 256]
        patch_size: [4, 16, 16]
        in_channels: 1
        hidden_size: 768
        num_heads: 8
        vision_select_layer: -1
        vision_select_feature: cls_patch

    projector:
      image_size: [32, 256, 256]
      patch_size: [4, 16, 16]
      out_channels: 256
      in_channels: 2048

      in_embed: 768
      # hidden_size: 1024
      hiddend_dim: 1072
      out_embed: 3072

      layer_type: mlp
      layer_num: 1
      pooling_type: spatial
      pooling_size: 2
      mm_projector_type: spp
  
training:
  output_dir: "./output"
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 4
  # num_train_epochs: 3
  max_steps: 2000
  logging_dir: "./logs"  
  eval_strategy: "steps"
  eval_steps: 40
  logging_steps: 40
  save_steps: 40
  # eval_steps: 2
  # logging_steps: 2  
  # save_steps: 2
  save_strategy: "steps"
  learning_rate: 1e-4
  weight_decay: 0.01
  warmup_ratio: 0.1
  lr_scheduler_type: "cosine"
  gradient_accumulation_steps: 2
  gradient_checkpointing: false
  dataloader_num_workers: 4
  save_total_limit: 2
  load_best_model_at_end: true
  report_to: wandb
  remove_unused_columns: false
  seed: 42
  fp16: False
  bf16: False
  metric_for_best_model: loss
  greater_is_better: False
  save_safetensors: False
  dataloader_pin_memory: False